#############################################################################
# Makefile for building: OOF.app/Contents/MacOS/OOF
# Generated by qmake (3.1) (Qt 5.12.0)
# Project:  OOF.pro
# Template: app
# Command: /Users/Travis/Qt/5.12.0/clang_64/bin/qmake -o Makefile OOF.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt/5.12.0/clang_64/mkspecs/macx-clang -F/Users/Travis/Qt/5.12.0/clang_64/lib
QMAKE         = /Users/Travis/Qt/5.12.0/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/Travis/Qt/5.12.0/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/Travis/Qt/5.12.0/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = OOF1.0.0
DISTDIR = /Users/Travis/Desktop/OOF_project/OOF-saddleback-cs1c/.tmp/OOF1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/Travis/Qt/5.12.0/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/Travis/Qt/5.12.0/clang_64/lib -framework QtWidgets,_debug -framework QtGui,_debug -framework QtCore,_debug -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		adminlogin.cpp \
		shape.cpp \
		canvas.cpp \
		contact.cpp qrc_images.cpp \
		moc_mainwindow.cpp \
		moc_adminlogin.cpp \
		moc_contact.cpp
OBJECTS       = main.o \
		mainwindow.o \
		adminlogin.o \
		shape.o \
		canvas.o \
		contact.o \
		qrc_images.o \
		moc_mainwindow.o \
		moc_adminlogin.o \
		moc_contact.o
DIST          = shape.txt \
		../../../Qt/5.12.0/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.12.0/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.12.0/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.12.0/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.12.0/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.12.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.12.0/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.12.0/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.12.0/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.12.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/mac/mac.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/lex.prf \
		OOF.pro mainwindow.h \
		adminlogin.h \
		shape.h \
		vector.h \
		canvas.h \
		contact.h \
		readfile.h main.cpp \
		mainwindow.cpp \
		adminlogin.cpp \
		shape.cpp \
		canvas.cpp \
		contact.cpp
QMAKE_TARGET  = OOF
DESTDIR       = 
TARGET        = OOF.app/Contents/MacOS/OOF

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.14
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


include /Users/Travis/Qt/5.12.0/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

OOF.app/Contents/MacOS/OOF: ui_mainwindow.h ui_adminlogin.h ui_contact.h $(OBJECTS)  
	@test -d OOF.app/Contents/MacOS/ || mkdir -p OOF.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: OOF.pro ../../../Qt/5.12.0/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.12.0/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.12.0/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.12.0/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.12.0/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.12.0/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.12.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.12.0/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.12.0/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.12.0/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.12.0/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.12.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/mac/mac.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.12.0/clang_64/mkspecs/features/lex.prf \
		OOF.pro \
		images.qrc
	$(QMAKE) -o Makefile OOF.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../../Qt/5.12.0/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.12.0/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.12.0/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.12.0/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.12.0/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.12.0/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.12.0/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.12.0/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.12.0/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.12.0/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.12.0/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.12.0/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.12.0/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.12.0/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.12.0/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.12.0/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/toolchain.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/qml_debug.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/mac/mac.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/qmake_use.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.12.0/clang_64/mkspecs/features/lex.prf:
OOF.pro:
images.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile OOF.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

OOF.app/Contents/PkgInfo: 
	@test -d OOF.app/Contents || mkdir -p OOF.app/Contents
	@$(DEL_FILE) OOF.app/Contents/PkgInfo
	@echo "APPL????" > OOF.app/Contents/PkgInfo
OOF.app/Contents/Resources/empty.lproj: 
	@test -d OOF.app/Contents/Resources || mkdir -p OOF.app/Contents/Resources
	@touch OOF.app/Contents/Resources/empty.lproj
	
OOF.app/Contents/Info.plist: 
	@test -d OOF.app/Contents || mkdir -p OOF.app/Contents
	@$(DEL_FILE) OOF.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.OOF,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.OOF,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,OOF,g" -e "s,@LIBRARY@,OOF,g" -e "s,\$${EXECUTABLE_NAME},OOF,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../../Qt/5.12.0/clang_64/mkspecs/macx-clang/Info.plist.app >OOF.app/Contents/Info.plist

all: Makefile \
		OOF.app/Contents/PkgInfo \
		OOF.app/Contents/Resources/empty.lproj \
		OOF.app/Contents/Info.plist OOF.app/Contents/MacOS/OOF

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents images.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Qt/5.12.0/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h adminlogin.h shape.h vector.h canvas.h contact.h readfile.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp adminlogin.cpp shape.cpp canvas.cpp contact.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui adminlogin.ui contact.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r OOF.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		../../../Qt/5.12.0/clang_64/bin/rcc \
		img/oof_logo.jpg
	/Users/Travis/Qt/5.12.0/clang_64/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Qt/5.12.0/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h ../../../Qt/5.12.0/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_adminlogin.cpp moc_contact.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_adminlogin.cpp moc_contact.cpp
moc_mainwindow.cpp: ../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		adminlogin.h \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		canvas.h \
		readfile.h \
		shape.h \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPaintDevice \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		vector.h \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		contact.h \
		mainwindow.h \
		moc_predefs.h \
		../../../Qt/5.12.0/clang_64/bin/moc
	/Users/Travis/Qt/5.12.0/clang_64/bin/moc $(DEFINES) --include /Users/Travis/Desktop/OOF_project/OOF-saddleback-cs1c/moc_predefs.h -I/Users/Travis/Qt/5.12.0/clang_64/mkspecs/macx-clang -I/Users/Travis/Desktop/OOF_project/OOF-saddleback-cs1c -I/Users/Travis/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers -I/Users/Travis/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers -I/Users/Travis/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -F/Users/Travis/Qt/5.12.0/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_adminlogin.cpp: ../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		adminlogin.h \
		moc_predefs.h \
		../../../Qt/5.12.0/clang_64/bin/moc
	/Users/Travis/Qt/5.12.0/clang_64/bin/moc $(DEFINES) --include /Users/Travis/Desktop/OOF_project/OOF-saddleback-cs1c/moc_predefs.h -I/Users/Travis/Qt/5.12.0/clang_64/mkspecs/macx-clang -I/Users/Travis/Desktop/OOF_project/OOF-saddleback-cs1c -I/Users/Travis/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers -I/Users/Travis/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers -I/Users/Travis/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -F/Users/Travis/Qt/5.12.0/clang_64/lib adminlogin.h -o moc_adminlogin.cpp

moc_contact.cpp: ../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		contact.h \
		moc_predefs.h \
		../../../Qt/5.12.0/clang_64/bin/moc
	/Users/Travis/Qt/5.12.0/clang_64/bin/moc $(DEFINES) --include /Users/Travis/Desktop/OOF_project/OOF-saddleback-cs1c/moc_predefs.h -I/Users/Travis/Qt/5.12.0/clang_64/mkspecs/macx-clang -I/Users/Travis/Desktop/OOF_project/OOF-saddleback-cs1c -I/Users/Travis/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers -I/Users/Travis/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers -I/Users/Travis/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -F/Users/Travis/Qt/5.12.0/clang_64/lib contact.h -o moc_contact.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_adminlogin.h ui_contact.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_adminlogin.h ui_contact.h
ui_mainwindow.h: mainwindow.ui \
		../../../Qt/5.12.0/clang_64/bin/uic \
		canvas.h \
		readfile.h \
		shape.h \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPaintDevice \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		vector.h \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	/Users/Travis/Qt/5.12.0/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_adminlogin.h: adminlogin.ui \
		../../../Qt/5.12.0/clang_64/bin/uic
	/Users/Travis/Qt/5.12.0/clang_64/bin/uic adminlogin.ui -o ui_adminlogin.h

ui_contact.h: contact.ui \
		../../../Qt/5.12.0/clang_64/bin/uic
	/Users/Travis/Qt/5.12.0/clang_64/bin/uic contact.ui -o ui_contact.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		adminlogin.h \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		canvas.h \
		readfile.h \
		shape.h \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPaintDevice \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		vector.h \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		contact.h \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		adminlogin.h \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		canvas.h \
		readfile.h \
		shape.h \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPaintDevice \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		vector.h \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		contact.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

adminlogin.o: adminlogin.cpp adminlogin.h \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_adminlogin.h \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adminlogin.o adminlogin.cpp

shape.o: shape.cpp shape.h \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPaintDevice \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		vector.h \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QtMath \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qmath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shape.o shape.cpp

canvas.o: canvas.cpp canvas.h \
		readfile.h \
		shape.h \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPaintDevice \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		vector.h \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o canvas.o canvas.cpp

contact.o: contact.cpp contact.h \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_contact.h \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contact.o contact.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_adminlogin.o: moc_adminlogin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adminlogin.o moc_adminlogin.cpp

moc_contact.o: moc_contact.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_contact.o moc_contact.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

